metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.137.0.10, mac: '00:15:5d:25:02:14', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 10.137.0.11, mac: '00:15:5d:10:f1:01', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 10.137.0.12, mac: '00:15:5d:10:f1:00', disk: sda, network_interface: eth0}
    workers:
      hosts:
        metal3: {ansible_host: 10.137.0.13, mac: '00:15:5d:25:02:13', disk: sda, network_interface: eth0}